env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 11
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
