#!/usr/bin/env bash

cd "${0%/*}"
BSC_VERBOSE=1
source utilities.sh

if command -v md5 >/dev/null; then
  md5Program=md5
elif command -v md5sum >/dev/null; then
  md5Program=md5sum
else
  errorMessage "Cannot find md5 or md5sum"
  exit 1
fi

yarn

rebuild_nodegit() {
  npm rebuild nodegit --target=8.3.3 --runtime=electron --dist-url='https://atom.io/download/electron' --update-binary -j 8
  if [ $? -ne 0 ]; then
    errorMessage "Cannot compile nodegit"
    exit 1
  fi
  echo "$($md5Program node_modules/nodegit/build/Release/nodegit.node)" >node_modules/nodegit/.rebuilt-for-electron
}

if [ ! -f "node_modules/nodegit/.rebuilt-for-electron" ]; then
  rebuild_nodegit
else
  if [ "$1" != '-f' ]; then
    if [ "$($md5Program node_modules/nodegit/build/Release/nodegit.node)" \
      == "$(cat node_modules/nodegit/.rebuilt-for-electron)" ]; then

      info 'Skipping nodegit as it has already been built for electron.'
      info 'run setup_env -f to force rebuild'
      info
    else
      rebuild_nodegit
    fi
  else
    rebuild_nodegit
  fi
fi


rebuild_font_scanner() {
  npm rebuild font-scanner --target=8.3.3 --runtime=electron --dist-url='https://atom.io/download/electron' --update-binary
  if [ $? -ne 0 ]; then
    errorMessage "Cannot compile font-scanner"
    exit 1
  fi
  echo "$($md5Program node_modules/font-scanner/build/Release/fontmanager.node)" >node_modules/font-scanner/.rebuilt-for-electron
}


if [ ! -f "node_modules/font-scanner/.rebuilt-for-electron" ]; then
  rebuild_font_scanner
else
  if [ "$1" != '-f' ]; then
    if [ "$($md5Program node_modules/font-scanner/build/Release/fontmanager.node)" \
      == "$(cat node_modules/font-scanner/.rebuilt-for-electron)" ]; then

      info 'Skipping font-scanner as it has already been built for electron.'
      info 'run setup_env -f to force rebuild'
      info
    else
      rebuild_font_scanner
    fi
  else
    rebuild_font_scanner
  fi
fi

rebuild_sqlite3() {
  npm rebuild sqlite3 --target=8.2.3 --runtime=electron --dist-url='https://atom.io/download/electron' --update-binary
  if [ $? -ne 0 ]; then
    errorMessage 'cannot rebuild sqlite3'
    exit 1
  fi
  platform=$(uname)
  oldPath="node_modules/sqlite3/lib/binding/electron-v8.2-$(echo $platform | awk '{print tolower($0)}')-x64/node_sqlite3.node"
  newPath="node_modules/sqlite3/lib/binding/electron-v8.3-$(echo $platform | awk '{print tolower($0)}')-x64/node_sqlite3.node"
  mkdir -p "node_modules/sqlite3/lib/binding/electron-v8.3-$(echo $platform | awk '{print tolower($0)}')-x64/"
  cp "$oldPath" "$newPath"
  echo "$($md5Program $newPath)" >node_modules/sqlite3/.rebuilt-for-electron
}

if [ ! -f "node_modules/sqlite3/.rebuilt-for-electron" ]; then
  rebuild_sqlite3

else
  if [ "$1" != '-f' ]; then
    platform=$(uname)
    libPath="node_modules/sqlite3/lib/binding/electron-v8.3-$(echo $platform | awk '{print tolower($0)}')-x64/node_sqlite3.node"
    if [ "$($md5Program $libPath)" \
      == "$(cat node_modules/sqlite3/.rebuilt-for-electron)" ]; then
      info 'Skipping sqlite3 as it has already been built for electron.'
      info 'run setup_env -f to force rebuild'
      info
    else
      rebuild_sqlite3
    fi
  else
    rebuild_sqlite3
    if [ $? -ne 0 ]; then
      errorMessage 'cannot rebuild sqlite3'
      exit 1
    fi
  fi
fi



# Canvas is required by jsdom for testing

rebuild_canvas() {
  npm rebuild canvas --target=8.3.3 --runtime=electron --dist-url='https://atom.io/download/electron' --update-binary
  if [ $? -ne 0 ]; then
    errorMessage 'cannot rebuild canvas'
    exit 1
  fi
  echo "$($md5Program node_modules/canvas/build/Release/canvas.node)" >node_modules/canvas/.rebuilt-for-electron
}

if [ ! -f "node_modules/canvas/.rebuilt-for-electron" ]; then
  rebuild_canvas

else
  if [ "$1" != '-f' ]; then
    if [ "$($md5Program node_modules/canvas/build/Release/canvas.node)" \
      == "$(cat node_modules/canvas/.rebuilt-for-electron)" ]; then
      info 'Skipping canvas as it has already been built for electron.'
      info 'run setup_env -f to force rebuild'
      info
    else
      rebuild_canvas
    fi
  else
    rebuild_canvas
    if [ $? -ne 0 ]; then
      errorMessage 'cannot rebuild canvas'
      exit 1
    fi
  fi
fi


