#! /bin/bash

cd "${0%/*}"
if [ $# -eq 0 ]
then
	echo "Usage: switch_binary.sh [72|76]"
fi

cd node_modules/nodegit/build 
if [ -L Release ]
then 
	rm Release
fi

if [ $1 -eq 72 ]
then
	ln -s Release_72 Release
elif [ $1 -eq 76 ]
then
	ln -s Release_76 Release
else
	echo "Version number must either be 72 or 76"
fi
