name: Test
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

defaults:
  run:
    shell: bash

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.13.0'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}
      
      - name: Update Apt
        run: sudo apt update
        
      - name: Install linux dependencies
        run: >
          sudo apt-get -y install build-essential clang libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          libkrb5-dev libdbus-1-dev libgtk-3-dev libnotify-dev libgnome-keyring-dev libasound2-dev
          libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl
          gperf bison python-dbusmock openjdk-8-jre

      - name: Run setup_env script
        run: ./setup_env
      - name: Run test
        run: yarn test
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.13.0'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}

      - name: Setup homebrew
        uses: artemnovichkov/action-homebrew@0.1.0

      - name: Install Dependencies
        run: brew install pixman

      - name: Run setup_env script
        run: ./setup_env
      - name: Run test
        run: yarn test
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.13.0'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}
      - name: Run setup_env script
        run: ./setup_env
      - name: Run test
        run: yarn test